package com.optum.gcm.dao.constants;

/**
 * @author pmule
 *
 */
public interface CodingWorkListQueries {

	/*String QUERY_GET_CODING_WORKLIST = "SELECT PC.GCM_PROJ_CONTENT_BARCODE CHART_ID, GCM_PROJ_CONT_BUS_FUNC_VEN_KEY, V.GCM_PROJECT_CONTENT_KEY, " 
										+"  PROV_GRP_NAME, " 
										+"  V.GCM_BUS_FUNC_STATUS CHART_STATUS, " 
										+"  V.GCM_HP_PRODUCT, " 
										+"  (SELECT HP_CD FROM GCM_HP H WHERE H.GCM_HP_KEY = V.GCM_HP_KEY " 
										+"  ) AS HP_CD, " 
										+"  (SELECT GCM_CLIENT_CD C " 
										+"  FROM GCM_CLIENT C, " 
										+"    GCM_HP H1 " 
										+"  WHERE C.GCM_CLIENT_KEY = H1.GCM_CLIENT_KEY " 
										+"  AND H1.GCM_HP_KEY      = V.GCM_HP_KEY " 
										+"  ) AS GCM_CLIENT_CD, " 
										+"  (SELECT GCM_PROGRAM_NAME " 
										+"  FROM GCMC.GCM_PROGRAM_LIST PL " 
										+"  WHERE PL.GCM_PROGRAM_KEY = V.GCM_PROGRAM_KEY " 
										+"  ) AS PROGRAM_NAME, " 
										+"  ASSIGNED_DATE_TIME AS ASSIGNED_DATE, " 
										+" V.GCM_BUS_FUNC_STATUS_DT, "
										+"  PC.PAGE_COUNT, " 
										+" GCM_BUSINESS_FUNC_KEY, "
										+"  PC.CHART_SCORE_GROUP, "
										+" V.QA_ACTION_CD,"
										+" CASE WHEN V.GCM_REASON_CODE IS NOT NULL THEN  'Y' "
										+" ELSE 'N' END ESCALATED_FLAG "
										+"FROM GCM_PROJ_CONT_BUS_FUNC_VENDOR V, " 
										+"  GCM_PROJ_CONTENT PC, " 
										+"  GCM_PROVIDER P " 
										+"WHERE P.GCM_PROVIDER_KEY             = V.GCM_PROVIDER_KEY " 
										+"AND PC.GCM_PROJECT_CONTENT_KEY       = V.GCM_PROJECT_CONTENT_KEY " 
										+"AND V.WORK_LIST_PARENT_ACTIVITY_KEY IS NULL " 
										+ " AND V.GCM_USER_KEY = :GCM_USER_KEY "
										+"AND V.GCM_BUSINESS_FUNC_KEY          = :GCM_BUSINESS_FUNC_KEY "
										+ " #WHERE# ORDER BY GCM_BUS_FUNC_STATUS_DT DESC " ;*/
	
	String QUERY_GET_CODING_WORKLIST = "SELECT * "
			+"  FROM TABLE(pkg_comm_worklist.fnc_worklist"
			+"  ( p_user_key              => :userKey,"
			+"    p_userid                => :userId,"
			+"    p_group_key             => :groupKey,"
			+"    p_vendor_key            => :vendorKey,"
			+"    p_role_code             => :roleCode,"
			+"    p_business_func_key     => :busFuncKey,"
			+"	  p_worklist_type		  => :workListType,"
			+"    p_bus_func_status       => :busFuncStatus,"
			+"    p_business_segment      => :busSegment,"
			+"    p_proj_key              => :projKey,"
			+"    p_client_key            => :clientKey,"
			+"    p_hp_key                => :hpKey,"
			+"    p_hp_product            => :hpProduct,"
			+"    p_program_key           => :programKey,"
			+"    p_barcode               => :chartId,"
			+"    p_accepted_from_date    => :fromDate,"
			+"    p_accepted_thru_date    => :toDate ))";
	
	String QUERY_UPDATE_CODING_RELEASETOASSIGN = "pkg_comm_assignment.prc_release_assignment" ;
	
	String QUERY_INSERT_CODERPROD_FORQA  = "INSERT " 
						+"INTO GCM_CODER_PRODUCTIVITY " 
						+"  ( " 
						+"    GCM_CODER_PRODUCTIVITY_KEY, " 
						+"    GCM_PROJ_CONT_BUS_FUNC_VEN_KEY, " 
						+"    GCM_PROJECT_CONTENT_KEY, " 
						+"    GCM_PROJ_CONTENT_BARCODE, " 
						+"    GCM_PROJ_KEY, " 
						+"    GCM_PROJECT_YEAR, " 
						+"    GCM_BUSINESS_FUNC_KEY, " 
						+"    GCM_VENDOR_KEY, " 
						+"    GCM_BUS_FUNC_STATUS, " 
						+"    EVENT, " 
						+"    WORK_ID, " 
						+"    WORK_LIST_PARENT_ACTIVITY_KEY, " 
						+"    GCM_ASSIGNEDBY_USER_KEY, "
						+"    GCM_USER_KEY, " 
						+"    CREATE_USERID, " 
						+"    CREATE_DATE_TIME, " 
						+"    MODIFY_USERID, " 
						+"    MODIFY_DATE_TIME " 
						+"  ) " 
						+"SELECT GCM_CODER_PRODUCTIVITY_SEQ.NEXTVAL, " 
						+"  GCM_PROJ_CONT_BUS_FUNC_VEN_KEY, " 
						+"  GCM_PROJECT_CONTENT_KEY, " 
						+"  GCM_PROJ_CONTENT_BARCODE, " 
						+"  GCM_PROJ_KEY, " 
						+"  GCM_PROJECT_YEAR, " 
						+"  GCM_BUSINESS_FUNC_KEY, " 
						+"  GCM_VENDOR_KEY, " 
						+"  GCM_BUS_FUNC_STATUS, " 
						+"  'ASSIGNED', " 
						+"  PKG_UTIL.FNC_GUID(), " 
						+"  WORK_LIST_PARENT_ACTIVITY_KEY, " 
						+"  :GCM_LOGIN_USER_KEY, "
						+"  :GCM_LOGIN_USER_KEY, " 
						+"  :MODIFY_USERID, " 
						+"  SYSDATE, " 
						+"  :MODIFY_USERID, " 
						+"  SYSDATE " 
						+"FROM GCM_PROJ_CONT_BUS_FUNC_VENDOR V " 
						+"WHERE V.GCM_PROJ_CONTENT_BARCODE IN "
						+" (SELECT REGEXP_SUBSTR (:CHARTIDS,'[^,]+',1,LEVEL) "  
						+"	FROM DUAL CONNECT BY REGEXP_SUBSTR (:CHARTIDS,'[^,]+',1,LEVEL) IS NOT NULL ) "
						+" AND V.GCM_BUSINESS_FUNC_KEY = :GCM_BUSINESS_FUNC_KEY "
                        +" AND V.WORK_LIST_PARENT_ACTIVITY_KEY IS NULL ";
	
}
