package com.optum.gcm.dao.constants;

public interface FaxQueryConstants {

	String QUERY_FAX_DOCUMENTID = "SELECT DOCUMENT_ID FROM GCM_RIGHTFAX_DETAILS WHERE GCM_RIGHTFAX_DETAILS_KEY "
			+ "IN (SELECT max(GCM_RIGHTFAX_DETAILS_KEY) FROM GCM_RIGHTFAX_DETAILS where GCM_RET_APPT_KEY = :GCM_RET_APPT_KEY)";

	String QUERY_FAX_HISTORY = "SELECT GCM_RET_APPT_KEY, DOCUMENT_ID, STATUS, MODIFY_DATE_TIME FROM GCM_RIGHTFAX_DETAILS "
			+ "WHERE GCM_RIGHTFAX_DETAILS_KEY IN "
			+ "(SELECT max(GCM_RIGHTFAX_DETAILS_KEY) FROM GCM_RIGHTFAX_DETAILS "
			+ "WHERE GCM_RET_APPT_KEY = :GCM_RET_APPT_KEY "
			+ "GROUP BY DOCUMENT_ID"
			+ ") ORDER BY MODIFY_DATE_TIME DESC";

	String UPDATE_CHARTS_AS_REFAX = "UPDATE GCM_RET_WI SET RFAX_SENT_STATUS  = CASE WHEN (RFAX_SENT_STATUS = 'REASSIGN') THEN 'REASSIGN_REFAX' ELSE 'REFAX' END, "
			+ "MODIFY_USERID = :MODIFY_USERID, MODIFY_DATE_TIME = SYSDATE WHERE GCM_PROJ_CONTENT_BARCODE IN (:CHARTIDS) ";
	
	String UPDATE_APPT_AS_REFAX = "UPDATE GCM_RET_WI SET RFAX_SENT_STATUS = 'REFAX', MODIFY_USERID = :MODIFY_USERID, MODIFY_DATE_TIME = SYSDATE WHERE GCM_RET_APPT_KEY = :GCM_RET_APPT_KEY AND NVL(RFAX_SENT_STATUS,'Z') NOT IN ('REASSIGN','REASSIGN_REFAX') ";

	
	String UPDATE_APPTSTS_AS_REFAX = "UPDATE GCM_RET_APPT SET FAX_STATUS = 'NEW', MODIFY_USERID = :MODIFY_USERID WHERE GCM_RET_APPT_KEY IN (SELECT GCM_RET_APPT_KEY FROM GCM_RET_WI WHERE GCM_PROJ_CONTENT_BARCODE IN (:CHARTIDS)) ";
	
}