package com.optum.gcm.dao.constants;

/**
 * @author pmule
 *
 */

public interface SchedulingWorlListQueries {

	String QUERY_GET_USER_SCHEDULIG_WORKLIST = "SELECT PROV_GRP_NAME, "
			+ "  PROV_NAME, " + "  PROV_ID, " + "  PROV_LOCATION, "
			+ "  PROV_PHONE, " + "  PROV_FAX, " + "  USER_NAME, "
			+ "  USER_KEY, " + "  REC_CNT, " + "  SPECIAL_CATEGORY, "
			+ "  SPECIAL_NOTES " + "FROM " + "  (SELECT P.PROV_GRP_NAME, "
			+ "    (P.PROV_LAST_NAME " + "    ||', ' "
			+ "    || P.PROV_FIRST_NAME)   AS PROV_NAME, "
			+ "    P.SOURCE_SYSTEM_PROV_ID AS PROV_ID, "
			+ "    PROVIDER_ADDRESS AS PROV_LOCATION, " + "    P.PROV_PHONE, "
			+ "    P.PROV_FAX, " + "    SPECIAL_CATEGORY AS SPECIAL_CATEGORY, "
			+ "    SPECIAL_NOTES AS SPECIAL_NOTES, " + "    (SELECT LAST_NAME "
			+ "      ||', ' " + "      ||FIRST_NAME " + "    FROM GCM_USER U "
			+ "    WHERE U.GCM_USER_KEY = WI.GCM_USER_KEY "
			+ "    ) AS USER_NAME, " + "    GCM_USER_KEY USER_KEY, "
			+ "    COUNT(1) REC_CNT " + "  FROM GCM_PROVIDER P, "
			+ "    GCM_RET_WI WI "
			+ "  WHERE WI.GCM_PROVIDER_KEY = P.GCM_PROVIDER_KEY "
			+ "  AND GCM_RET_APPT_KEY     IS NULL "
			+"   AND gcm_bus_func_status NOT IN ('CANCELED','DUPLICATE', 'RECVD','CNA') "
			+ "  AND GCM_USER_KEY IS NOT NULL "
			+ "  AND GCM_USER_KEY = :GCM_USER_KEY "
			+ "  AND GCM_BUS_FUNC_DETAIL_KEY = :GCM_BUS_FUNC_DETAIL_KEY "
			+ "  AND WI.GCM_HP_KEY        IN " + "    (SELECT GCM_HP_KEY "
			+ "    FROM GCM_GROUP_CLIENT_HP_VW "
			+ "    WHERE GCM_GROUP_KEY IN " + "      (SELECT GCM_GROUP_KEY "
			+ "      FROM GCM_USER_VENDOR_GROUP_VW "
			+ "      WHERE GCM_USER_KEY = :GCM_LOGIN_USER_KEY " + "      ) "
			+ "    ) #WHERE# " + "  GROUP BY P.PROV_GRP_NAME, "
			+ "    (P.PROV_LAST_NAME " + "    ||', ' "
			+ "    || P.PROV_FIRST_NAME), " + "    P.SOURCE_SYSTEM_PROV_ID, "
			+ "    PROVIDER_ADDRESS, " + "    SPECIAL_CATEGORY, "
			+ "    SPECIAL_NOTES, " + "    P.PROV_PHONE, " + "    P.PROV_FAX, "
			+ "    GCM_USER_KEY " + "  ORDER BY REC_CNT " + "  )";

	String QUERY_GET_MY_APPTS = "SELECT DISTINCT A.GCM_RET_APPT_KEY, " 
			+"  APPT_DATE_TIME, " 
			+"  CASE " 
			+"    WHEN COUNT(DISTINCT NVL(PROVIDER_ADDRESS,'^')) OVER ( PARTITION BY A.GCM_RET_APPT_KEY )=1 " 
			+"    THEN PROVIDER_ADDRESS " 
			+"    ELSE 'MULTIPLE' " 
			+"  END AS PROV_LOCATION, " 
			+"  CASE " 
			+"    WHEN COUNT(DISTINCT P.PROV_LAST_NAME " 
			+"      ||',' " 
			+"      ||P.PROV_FIRST_NAME) OVER ( PARTITION BY A.GCM_RET_APPT_KEY )=1 " 
			+"    THEN (P.PROV_LAST_NAME " 
			+"      ||', ' " 
			+"      ||P.PROV_FIRST_NAME) " 
			+"    ELSE 'MULTIPLE' " 
			+"  END AS PROV_NAME, " 
			+"  CASE " 
			+"    WHEN COUNT(DISTINCT PROV_GRP_NAME) OVER ( PARTITION BY A.GCM_RET_APPT_KEY ) =1 " 
			+"    THEN P. PROV_GRP_NAME " 
			+"    ELSE 'MULTIPLE' " 
			+"  END AS PROV_GRP_NAME, " 
			+"  A.APPT_STATUS, " 
			+"  A.FAX_STATUS, " 
			+"  A.CREATE_DATE_TIME, " 
			+"  COUNT( " 
			+"  CASE " 
			+"    WHEN WI.GCM_BUS_FUNC_STATUS IN ( 'RECVD' , 'NONRETRIEVABLE', 'CANCELED', 'DUPLICATE', 'INACTIVATED', 'CNA'  ) " 
			+"    THEN NULL " 
			+"    ELSE 1 " 
			+"  END) OVER ( PARTITION BY A.GCM_RET_APPT_KEY order by 1 )     AS CHART_NOT_RECVDCNT, " 
			+"  COUNT(*) OVER ( PARTITION BY A.GCM_RET_APPT_KEY order by 1 ) AS TOTAL_CNT,"
			+"  APPT_TYPE AS " 
			+"FROM GCM_RET_APPT A, " 
			+"  GCM_RET_WI WI, " 
			+"  GCM_PROVIDER P " 
			+"WHERE WI.GCM_RET_APPT_KEY   = A.GCM_RET_APPT_KEY " 
			+"AND P.GCM_PROVIDER_KEY      = WI.GCM_PROVIDER_KEY " 
			+"AND A.GCM_USER_KEY          = :GCM_USER_KEY " 
			+"AND A.GCM_VENDOR_KEY        = :GCM_VENDOR_KEY " 
			+"AND GCM_BUS_FUNC_DETAIL_KEY = :GCM_BUS_FUNC_DETAIL_KEY " 
			+"AND A.APPT_STATUS NOT      IN ('CANCELED','PEND', 'COMPLETED')  #WHERE# " 
			+"ORDER BY " 
			+"  CASE A.APPT_STATUS " 
			+"    WHEN 'PASTDUE' " 
			+"    THEN 1 " 
			+"    WHEN 'PEND RELEASED' " 
			+"    THEN 2 " 
			+"    WHEN 'INPROGRESS' " 
			+"    THEN 3 " 
			+"    WHEN 'SCHEDULED' " 
			+"    THEN 4 " 
			+"  END, "
			+ " A.CREATE_DATE_TIME DESC ";

	String QUERY_GET_WORKLIST_COUNTS = "SELECT RECEIVED_CNT, "
			+ "  INPROGRESS_CNT, "
			+ "  PASTDUE_CNT "
			+ "FROM "
			+ "  (SELECT GCM_RET_APPT_KEY, "
			+ "    CASE "
			+ "      WHEN APPT_STATUS IN ('RECVD') "
			+ "      THEN 'COMPLETED' "
			+ "      WHEN APPT_STATUS = 'PASTDUE' "
			+ "      THEN 'PASTDUE' "
			+ "       WHEN APPT_STATUS = 'INPROGRESS' "
			+" THEN 'INPROGRESS' "
	       	+" ELSE       'SCHEDULED' "
			+ "    END STATUS "
			+ "  FROM "
			+ "    (SELECT "
			+ "      A.APPT_STATUS, "
			+ "      WI.GCM_BUSINESS_FUNC_KEY, "
			+ "      WI.GCM_RET_APPT_KEY, "
			+ "      A.APPT_DATE_TIME, "
			+ "      ROW_NUMBER() OVER (PARTITION BY A.GCM_RET_APPT_KEY ORDER BY A.APPT_STATUS DESC) R_NUM "
			+ "    FROM GCM_RET_WI WI, "
			+ "      GCM_RET_APPT A "
			+ "    WHERE WI.GCM_BUSINESS_FUNC_KEY IN (4) #WHERE#"
			+ "    AND A.GCM_RET_APPT_KEY (+)      = WI.GCM_RET_APPT_KEY AND A.GCM_USER_KEY=:GCM_USER_KEY AND A.GCM_USER_KEY=WI.GCM_USER_KEY AND WI.GCM_BUS_FUNC_DETAIL_KEY =:GCM_BUS_FUNC_DETAIL_KEY "
			+ "    ) "
			+ "  WHERE R_NUM = 1 "
			+ "  ) PIVOT(COUNT(GCM_RET_APPT_KEY) FOR STATUS IN ( 'COMPLETED' AS RECEIVED_CNT, 'INPROGRESS' AS INPROGRESS_CNT, 'PASTDUE' AS PASTDUE_CNT))";

}
